models/book.py
import os
import uuid
from pathlib import Path
from sqlalchemy import Column, String, Integer, ForeignKey
from sqlalchemy.orm import relationship

from models.base import Base
import models.user

def upload_file(file, filename):
    path = Path.joinpath(Path(__file__).parent.parent, 'static/images')
    file.save(Path.joinpath(path, filename))


def delete_file(filename):
    path = Path.joinpath(Path(__file__).parent.parent, 'static/images')
    os.remove(Path.joinpath(path, filename))


class Book(Base):
    __tablename__ = 'book'
    id = Column(String(255), primary_key=True)
    title = Column(String(255))
    isbn = Column(String(255))
    category = Column(String(255))
    filename = Column(String(255))
    author = Column(String(255))
    num_of_pages = Column(Integer)
    user_id = Column(String(255), ForeignKey("users.id"))
    user = relationship("User", back_populates="books")

    def __init__(self, title, isbn, category, filename, author, num_of_pages, user_id, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.id = str(uuid.uuid4())
        self.title: str = title
        self.isbn: str = isbn
        self.category: str = category
        self.filename: str = filename
        self.author: str = author
        self.num_of_pages: int = num_of_pages
        self.user_id: str = user_id

    def to_json(self, type: str):
        if type == 'list':
            return {
                'id': self.id,
                'title': self.title,
                'author': self.author,
                'user_id': self.user_id
            }
        elif type == 'show':
            return {
                'id': self.id,
                'title': self.title,
                'author': self.author,
                'isbn': self.isbn,
                'category': self.category,
                'num_of_pages': self.num_of_pages
            }

blueprints/books.py
import os
import uuid

from flask import Blueprint, render_template, make_response, redirect, url_for
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
from forms.CreateForm import CreateForm
from forms.UpdateForm import UpdateForm
from models.book import Book, upload_file, delete_file
from repository.book_repository import BookRepository

books = Blueprint('books', __name__, url_prefix='/books')


@books.get('/<book_id>')
@login_required
def show(book_id):
    try:
        book_repository = BookRepository()
        book = book_repository.get(book_id)

        if book is None:
            raise ValueError(f"Book with id {book_id} doesn't exist")

        return render_template('books/show.html', book=book)
    except Exception as e:
        return make_response(e.__str__(), 400)


@books.get('/')
@login_required
def display_list():
    try:
        user = current_user
        book_repository = BookRepository()
        book_list = book_repository.list()
        list_books = [book.to_json('list') for book in book_list]

        return render_template('books/list.html', list_books=list_books, user=user)
    except Exception as e:
        return make_response(e.__str__(), 400)


@books.get('/update/<book_id>')
@login_required
def update_template(book_id):
    try:
        book_repository = BookRepository()
        book = book_repository.get(book_id)
        form = UpdateForm(obj=book)

        return render_template('books/edit.html', form=form)
    except Exception as e:
        return make_response(e.__str__(), 400)


@books.post('/update/<book_id>')
@login_required
def update_book(book_id):
    try:
        form = UpdateForm()
        if form.validate_on_submit():
            params = {
                'title': form.title.data,
                'isbn': form.isbn.data,
                'category': form.category.data,
                'author': form.author.data,
                'num_of_pages': form.num_of_pages.data,
            }

            if form.image.data is not None:
                filename = str(uuid.uuid4()) + '_' + secure_filename(form.image.data.filename)
                params['filename'] = filename
                upload_file(form.image.data, filename)

            book_repository = BookRepository()
            book = book_repository.get(book_id)

            if book is None:
                raise ValueError(f"Book with id: {book_id} doesn't exist", 404)

            if book.user_id != current_user.id:
                raise ValueError("Unauthorized", 401)

            book_repository.update(book, params)

            return redirect(url_for('books.show', book_id=book_id))

        return render_template('books/edit.html', form=form)
    except Exception as e:
        return make_response(e.__str__(), 400)


@books.get('/add')
@login_required
def add_template():
    form = CreateForm()
    return render_template('books/add.html', form=form)


@books.post('/add')
@login_required
def add_book():
    try:
        form = CreateForm()

        if form.validate_on_submit():
            title = form.title.data
            isbn = form.isbn.data
            category = form.category.data
            author = form.author.data
            filename = str(uuid.uuid4()) + '_' + secure_filename(form.image.data.filename)
            upload_file(form.image.data, filename)
            num_of_pages = form.num_of_pages.data
            user_id = current_user.id

            book = Book(title, isbn, category, filename, author, num_of_pages, user_id)
            book_repository = BookRepository()
            book_repository.add(book)

            return redirect(url_for('books.show', book_id=book.id))

        return render_template('books/add.html', form=form)
    except Exception as e:
        return make_response(e.__str__(), 400)


@books.delete('/delete/<book_id>')
@login_required
def remove_book(book_id):
    try:
        book_repository = BookRepository()
        book = book_repository.get(book_id)
        if book is None:
            raise ValueError(f"Book with id: {book_id} doesn't exist", 404)
        if book.user_id != current_user.id:
            raise ValueError("Unauthorized", 401)

        delete_file(book.filename)
        book_repository.delete(book)

        return make_response('book deleted', 200)

    except Exception as e:
        return make_response(e.__str__(), 400)

templates/books/add.html
{% extends 'base.html' %}

{% block title %}Añadir{% endblock %}

{% block content %}
    <div class="container">
        <div class="h1 mt-3">
            <span>Nuevo libro</span>
        </div>
        <hr>
        <div class="d-flex w-100 justify-content-center">
            <div class="col-12 col-sm-7 col-lg-4">
                <div class="border border-1 p-5 rounded-4 w-100 h-100 mt-4">
                    <form action="{{ url_for('books.add_book') }}" method="post" enctype="multipart/form-data">
                        {% include 'books/_partial/form_data.html' %}
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/books/edit.html
{% extends 'base.html' %}

{% block title %}Books{% endblock %}

{% block content %}
    <div class="container">
        <div class="h1 mt-3">
            <span>Nuevo libro</span>
        </div>
        <hr>
        <div class="d-flex w-100 justify-content-center">
            <div class="col-12 col-sm-7 col-lg-4">
                <div class="border border-1 p-5 rounded-4 w-100 h-100 mt-4">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% include 'books/_partial/form_data.html' %}
                        <div>
                            {{ form.id }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/books/list.html
{% extends 'base.html' %}

{% block title %}Books{% endblock %}

{% block stylesheets %}
    <link href="{{ url_for('static', filename='css/book-list.css') }}" type="text/css" rel="stylesheet">
{% endblock %}
{% block javascript %}
    <script src="{{ url_for('static', filename='js/list.js') }}" type="application/javascript"></script>
{% endblock %}

{% block content %}
    <input id="csrf_token" type="hidden" value="{{ csrf_token() }}">
    <div class="container">
        <div class="h1 mt-3">
            <span>Mi Biblioteca</span>
        </div>
        <hr>
        <div class="d-flex-inline row justify-content-center">
            <div class="col-12 col-sm-10 col-lg-8">
                {% for book in list_books %}
                    {% if book.user_id == g.user.id %}
                        <div class="d-flex shadow-sm w-100 border border-1 rounded-3 p-4 mt-3">
                            <div class="d-flex flex-grow-1">
                                <a class="text-decoration-none fs-4 text-black-50"
                                   href="{{ url_for('books.show', book_id=book.id) }}"><span
                                        class="align-self-center">{{ book.title }}</span></a>
                            </div>
                            <div class="d-flex flex-shrink-1">
                                <a class="btn btn-warning d-flex justify-content-center px-1 me-2"
                                   href="{{ url_for('books.update_template', book_id=book.id) }}"><i
                                        class="d-flex edit-icon h-75 w-75 align-self-center"></i></a>
                                <button class="btn btn-outline-danger d-flex justify-content-center px-2 me-2 trash-icon"
                                        data-id="{{ book.id }}">
                                    <i class="delete-icon h-75 w-75 align-self-center"></i></button>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/books/show.html
{% extends 'base.html' %}

{% block title %}Book{% endblock %}

{% block content %}
    <div class="container d-flex justify-content-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4 mt-4">
            <img class="w-100 pe-3" src="{{ url_for('static', filename='images/' + book.filename ) }}"
                 alt="{{ book.filename }}">
        </div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
            <div class="d-flex-inline border border-1 rounded-3 p-3 mt-4">
                <table class="table fs-5">
                    <tr>
                        <td>Id</td>
                        <td>{{ book.id }}</td>
                    </tr>
                    <tr>
                        <td>Title</td>
                        <td>{{ book.title }}</td>
                    </tr>
                    <tr>
                        <td>ISBN</td>
                        <td>{{ book.isbn }}</td>
                    </tr>
                    <tr>
                        <td>Category</td>
                        <td>{{ book.category }}</td>
                    </tr>
                    <tr>
                        <td>Author</td>
                        <td>{{ book.author }}</td>
                    </tr>
                    <tr>
                        <td>Pages</td>
                        <td>{{ book.num_of_pages }}</td>
                    </tr>
                    <tr>
                        <td>User</td>
                        <td>{{ book.user.username }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}